In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv("Movie_classification.csv" , header=0)
df.head()


# Missing values information
df.info()
# Time_taken 494 non-null float64
#missing value imputation with mean values

df["Time_taken"].fillna(value=df["Time_taken"].mean() , inplace = True)

#Rechecking the whether missing values or imputed or not
df.info()

#Dummy value creation for "3d_avaiable" , "Genre" columns

df= pd.get_dummies(df , columns =["3D_available" , "Genre"], drop_first=True)

#Checking the dummi variable

df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB
<class 

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating       ...        Time_taken  \
0            7.995           7.94       ...            109.60   
1            7.470           7.44       ...            146.64   
2            7.515           7.44       ...            147.88   
3            7.020           8.26       ...            185.36   
4            7.070           8.26       ...            176.48   

   Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
0          223.840              23            494       48000   
1          243.456              42            462       43200   
2         2022.400              38            458       69400   
3          225.344              45            472       66800   
4          225.792              55            395       72400   

   Start_Tech_Oscar  3D_available_YES  Genre_Comedy  Genre_Drama  \
0                 1                 1             0            0   
1                 0                 0             0            1   
2                 1                 0             1            0   
3                 1                 1             0            1   
4                 1                 0             0            1   

   Genre_Thriller  
0               1  
1               0  
2               0  
3               0  
4               0  

[5 rows x 21 columns]

## X-y Split

In [2]:
from sklearn.model_selection import train_test_split
#Independent variables
X = df.loc[:, df.columns!= "Start_Tech_Oscar"]
type(X)
X.head()
X.shape
#Dependent variable 
y = df["Start_Tech_Oscar"]
type(y)
y.head()
y.shape

# Train_test_split
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2 , random_state=0)

X_train.shape #(404,19)
X_test.shape #(102,19)
y_train.shape #(404)
y_test.shape  #(102)

(102,)

## Standardizing The Data

In [3]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [4]:
X_test_std 

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training Model

https://scikit-learn.org/stable/modules/sklearn.svm.SVC.html

In [5]:
from sklearn import svm

In [6]:
clf_svm_1 = svm.SVC(kernel='linear' , C=0.01)
clf_svm_1.fit(X_train_std , y_train)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
y_train_pred = clf_svm_1.predict(X_train_std)
y_test_pred = clf_svm_1.predict(X_test_std)

In [8]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [10]:
confusion_matrix(y_test,y_test_pred)

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [11]:
accuracy_score(y_test,y_test_pred)

0.6274509803921569

In [12]:
clf_svm_1.n_support_   # first parameter is called support vectors for 0 class in Start_Tech_Oscar
                    # 189 represents number of support vectors in 1 class in Start_Tech_Oscar

array([186, 189])

In [13]:
clf_svm_1.support_vectors_

array([[-0.40576883, -0.46581859,  0.27712701, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.41106174,  0.11548094, -0.14874564, ..., -0.66547513,
        -0.48525664, -0.75225758],
       [-0.39884697, -0.46581859,  0.27712701, ..., -0.66547513,
         2.06076521, -0.75225758],
       ...,
       [-0.41493237, -1.52676181,  1.16363741, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.38169978, -0.53597543,  0.54655664, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.38842357, -0.60326872,  0.93766417, ..., -0.66547513,
        -0.48525664,  1.3293319 ]])

## Grid Search

In [14]:
from sklearn.model_selection import GridSearchCV
params = {'C':(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5 , 10 , 50, 100, 500, 1000)}

In [15]:
clf_svm_2 = svm.SVC(kernel='linear')

In [16]:
svm_grid_lin = GridSearchCV(clf_svm_2, params , n_jobs=-1 , cv=10, verbose=1, scoring='accuracy')

In [17]:
svm_grid_lin.fit(X_train_std, y_train) # because of the verbose=1 we are getting ouput of this cell

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:  2.7min finished


GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [18]:
svm_grid_lin.best_params_

{'C': 0.5}

In [19]:
linsvm_clf = svm_grid_lin.best_estimator_

In [20]:
accuracy_score(y_test,linsvm_clf.predict(X_test_std))

0.5980392156862745

# polynomial

In [34]:
clf_svm_p3 = svm.SVC(kernel='poly',degree=3, C=0.1)
clf_svm_p3.fit(X_train_std, y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [35]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [36]:
accuracy_score(y_test,y_test_pred)

0.5784313725490197

In [37]:
clf_svm_p3.n_support_

array([185, 198])

## Radial Kernel

In [38]:
clf_svm_r = svm.SVC(kernel="rbf", gamma=0.5, C=10)
clf_svm_r.fit(X_train_std,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
y_train_pred = clf_svm_r.predict(X_train_std)
y_test_pred = clf_svm_r.predict(X_test_std)

In [42]:
accuracy_score(y_test,y_test_pred)

0.6176470588235294

## Radial Grid

In [48]:
from sklearn.model_selection import GridSearchCV
params = {'C':(0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
         'gamma':(0.001, 0.01, 0.1, 0.5, 1)}

In [49]:
clf_svm_r_1 = svm.SVC(kernel='rbf')

In [56]:
svm_grid_rad = GridSearchCV(clf_svm_r_1, params , n_jobs=-1, cv=10, verbose=1, scoring='accuracy')

In [57]:
svm_grid_rad.fit(X_train_std, y_train)

Fitting 10 folds for each of 40 candidates, totalling 400 fits


[Parallel(n_jobs=-1)]: Done  48 tasks      | elapsed:   14.0s
[Parallel(n_jobs=-1)]: Done 400 out of 400 | elapsed:   15.9s finished


GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50), 'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [58]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [59]:
radsvm_clf = svm_grid_rad.best_estimator_

In [60]:
accuracy_score(y_test, radsvm_clf.predict(X_test_std))

0.6176470588235294